uaa:
  signing-key: uaa

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  application:
    name: soy-uaa
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/soy?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver