server:
  port: 9071
sys:
  demo: false
spring:
  application:
    name: soy-route
  profiles:
    active: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"