spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    ssl: false
    timeout: 3000
  security:
    oauth2:
      resourceserver:
        jwt:
          # 获取JWT验签公钥请求路径
          jwk-set-uri: 'http://localhost:8000/getPublicKey'
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: b8cb24a7-9551-48d2-86d3-12051a78453a
        group: ${spring.profiles.active}
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
         - id: soy-auth
           uri: lb://soy-auth
           predicates:
             - Path=/soy-auth/**
           filters:
             - StripPrefix=1
#        - id: route
#          uri: http://localhost:8080
#          predicates:
#            - Path=/route/**
#          filters:
#            - StripPrefix=1
#            - name: CircuitBreaker
#              args:
#                name: defaultCustomizer
#                fallbackUri: forward:/fallback/wrong

# 配置白名单路径
white-list:
  urls:
    - "/soy-auth/oauth/token"
# 配置白名单路径
black-list:
  urls: