spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
#      routes:
#        - id: route
#          uri: http://localhost:8080
#          predicates:
#            - Path=/route/**
#          filters:
#            - StripPrefix=1
#            - name: CircuitBreaker
#              args:
#                name: defaultCustomizer
#                fallbackUri: forward:/fallback/wrong
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ec36d5a3-ae85-43b5-bc3f-67fd3d0d625d
        group: ${spring.profiles.active}